### ISSUE TITLE
Error on starting example on Windows

### ISSUE THREAD

**Issue by rkeates** [eclipse-emfcloud/ecore-glsp#112]
I am starting the example on windows, I cloned the repo and build the project with ./build.sh.

There are no errors during building, the errors are only present once the client is started.

I am running:
Windows 10 Pro 20H2
Java  11.0.11+9
Apache Maven 3.8.1

When running the client using yarn start I get the following errors:

``` shell
ERROR DefaultModelResourceManager  - Could not load resource with URI: /Project/Theia/ecore-glsp/client/workspace/ecore/m
odel/ecore.ecore
java.lang.NullPointerException
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.loadResour
ce(DefaultModelResourceManager.java:166)
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelRepository.getModel(Defaul
tModelRepository.java:69)
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.getOne(DefaultM
odelController.java:128)
        at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.lambda$43(ModelSe
rverRoutingV1.java:245)
        at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
        at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.getModel(ModelSer
verRoutingV1.java:244)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet
.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:4
9)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:1
79)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.
java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:
338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.jav
a:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.ja
va:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedTh
readExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:10
34)
        at java.base/java.lang.Thread.run(Unknown Source)
```

The project starts up but has additional errors in the browser, notification of error in Theia:

```
java.lang.NullPointerException
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelState.getEcoreFacade(EcoreModelState.java:49)
	at org.eclipse.emfcloud.ecore.glsp.handler.RequestSemanticUriActionHandler.executeAction(RequestSemanticUriActionHandler.java:29)
	at org.eclipse.emfcloud.ecore.glsp.handler.RequestSemanticUriActionHandler.executeAction(RequestSemanticUriActionHandler.java:1)
	at org.eclipse.glsp.server.actions.BasicActionHandler.execute(BasicActionHandler.java:45)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runAction(DefaultActionDispatcher.java:210)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleMessage(DefaultActionDispatcher.java:180)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleNextMessage(DefaultActionDispatcher.java:165)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runThread(DefaultActionDispatcher.java:152)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by agonzalezgaliana** [comment]
Same issue here in a Windows 10 machine.

After starting the client with `yarn start` I'm able to open Theia on `localhost:3000`. The following error appears on the console as soon as I open an `*.ecore` file:

```
root INFO ModelServerBackendContribution: 5046 [qtp70165127-31] ERROR DefaultModelResourceManager  - Could not load resource with URI: /Development/eclipse-theia-dev-workspaces/eclipse-emfcloud/ecore-glsp/client/workspace/empty/model/empty.ecore
java.lang.NullPointerException
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.loadResource(DefaultModelResourceManager.java:166)
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelRepository.getModel(DefaultModelRepository.java:69)
        at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.getOne(DefaultModelController.java:128)
        at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.lambda$43(ModelServerRoutingV1.java:245)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
        at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.getModel(ModelServerRoutingV1.java:244)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:829)

root INFO ModelServerBackendContribution: 5048 [qtp70165127-31] ERROR ContextResponse  - Model '/Development/eclipse-theia-dev-workspaces/eclipse-emfcloud/ecore-glsp/client/workspace/empty/model/empty.ecore' not found!
5049 [qtp70165127-31] INFO ProviderDefaults  - GET /api/v1/models?modeluri=c%3A%2FDevelopment%2Feclipse-theia-dev-workspaces%2Feclipse-emfcloud%2Fecore-glsp%2Fclient%2Fworkspace%2Fempty%2Fmodel%2Fempty.ecore&format=xmi -> Status: 404 (took 7.7421 ms)
```

Not sure, but perhaps the problem is related with Windows file path

**Comment by rkeates** [comment]
I tried the same solution on Ubuntu 20.04.2 LTS (VM) with all the prerequisites installed and it works without errors.

**Comment by CamilleLetavernier** [comment]
Hi,

Thanks for reporting the issue. Unfortunately, Ecore GLSP is largely untested on Windows. We probably need to change the way file paths are computed, to support both Windows and Linux paths.

**Comment by agonzalezgaliana** [comment]
Hi @CamilleLetavernier ,

perhaps it would make sense to mention that in the README.md file to warn other developers.
From my side I'm currently doing lots of research on GLSP because the technology seems very interesting in combination with Eclipse Theia. I'm coming from other Theia tutorials that work well in Windows and it's a pity not to be able to test this example.

Regards.

**Comment by JonasHelming** [comment]
We are looking into this and hopefully provide a fix soon.

**Comment by harmen-xb** [comment]
Because of the issues when running ecore-glsp on Windows I updated the Dockerfile so it works again and added some more detailed instructions for users to get started:

https://github.com/eclipse-emfcloud/ecore-glsp/pull/120
