### ISSUE TITLE
NewEClass1Container [GLSP-Server] Could not process message:ActionMessage [action=compound

### ISSUE THREAD

**Issue by Deel96** [eclipse-emfcloud/ecore-glsp#125]
I build and started ecore-glsp according to the docs. In this process I also get error messages like 

```
root WARN Failed to resolve module: filenamify

Missing dependency 'Slf4j simple with Provider'. Add the dependency.

pom.xml:
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.8.0-beta4</version>
</dependency>

build.gradle:
compile "org.slf4j:slf4j-api:1.8.0-beta4"

Find the latest version here:
https://search.maven.org/search?q=g%3Aorg.slf4j+AND+a%3Aslf4j-api
------------------------------------------------------------------- and

-------------------------------------------------------------------
Missing dependency 'Slf4j simple with Provider'. Add the dependency.

pom.xml:
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.8.0-beta4</version>
</dependency>

build.gradle:
compile "org.slf4j:slf4j-simple:1.8.0-beta4"

Find the latest version here:
https://search.maven.org/search?q=g%3Aorg.slf4j+AND+a%3Aslf4j-simple

```

But I can use the application on localhost:3000

After that I created a Abstract Class and when I move it I get following error:
![image](https://user-images.githubusercontent.com/37439779/181487193-41470800-3afe-4c6e-8157-5a547771edac.png)

Details:

```AClass
AClass
[GLSP-Server] Could not process message:ActionMessage [action=compound, clientId=ecorediagram:file:///home/user/GIT/ecore-glsp/client/workspace/sat/model/sat.ecore]

class org.eclipse.emf.common.command.UnexecutableCommand cannot be cast to class org.eclipse.emf.edit.command.SetCommand (org.eclipse.emf.common.command.UnexecutableCommand is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2ce6c6ec; org.eclipse.emf.edit.command.SetCommand is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @19b1fe52)
java.lang.ClassCastException: class org.eclipse.emf.common.command.UnexecutableCommand cannot be cast to class org.eclipse.emf.edit.command.SetCommand (org.eclipse.emf.common.command.UnexecutableCommand is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2ce6c6ec; org.eclipse.emf.edit.command.SetCommand is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @19b1fe52)
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelServerAccess.createSetCommand(EcoreModelServerAccess.java:441)
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelServerAccess.lambda$2(EcoreModelServerAccess.java:463)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelServerAccess.setBounds(EcoreModelServerAccess.java:451)
	at org.eclipse.emfcloud.ecore.glsp.operationhandler.EcoreChangeBoundsOperationHandler.executeOperation(EcoreChangeBoundsOperationHandler.java:35)
	at org.eclipse.emfcloud.ecore.glsp.operationhandler.EcoreChangeBoundsOperationHandler.executeOperation(EcoreChangeBoundsOperationHandler.java:1)
	at org.eclipse.emfcloud.ecore.glsp.operationhandler.ModelServerAwareBasicOperationHandler.executeOperation(ModelServerAwareBasicOperationHandler.java:41)
	at org.eclipse.glsp.server.operations.BasicOperationHandler.execute(BasicOperationHandler.java:41)
	at org.eclipse.glsp.server.operations.gmodel.CompoundOperationHandler.executeNestedOperation(CompoundOperationHandler.java:43)
	at org.eclipse.glsp.server.operations.gmodel.CompoundOperationHandler.lambda$0(CompoundOperationHandler.java:36)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.eclipse.glsp.server.operations.gmodel.CompoundOperationHandler.executeOperation(CompoundOperationHandler.java:36)
	at org.eclipse.glsp.server.operations.gmodel.CompoundOperationHandler.executeOperation(CompoundOperationHandler.java:1)
	at org.eclipse.glsp.server.operations.BasicOperationHandler.execute(BasicOperationHandler.java:41)
	at org.eclipse.emfcloud.ecore.glsp.handler.EcoreOperationActionHandler.executeHandler(EcoreOperationActionHandler.java:40)
	at org.eclipse.emfcloud.ecore.glsp.handler.EcoreOperationActionHandler.executeAction(EcoreOperationActionHandler.java:32)
	at org.eclipse.glsp.server.operations.OperationActionHandler.executeAction(OperationActionHandler.java:1)
	at org.eclipse.glsp.server.actions.BasicActionHandler.execute(BasicActionHandler.java:45)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runAction(DefaultActionDispatcher.java:210)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleMessage(DefaultActionDispatcher.java:180)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleNextMessage(DefaultActionDispatcher.java:165)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runThread(DefaultActionDispatcher.java:152)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

After my research the error regarding "filenamify" seems to be not severe.

Here are the logs from the server after running yarn and yarn start:

https://pastebin.com/m8FXPjEv

**Comment by ndoschek** [comment]
Hi again @Deel96!

I tested with the current master of `@eclipse-emfcloud/ecore-glsp` and cannot reproduce your described issue.
I created a new Ecore model (which contains a new `*.ecore` and `*.enotation` file), added a new element (an abstract class in that case) and moved it on the canvas.
I did not get any errors, also undo/redo works without any issues.

- Did you make any changes to the project?
- Are there any additional steps you made that were not described?

Thanks and BR, Nina

**Comment by Deel96** [comment]
Hi @ndoschek  Thank you for pointing me to the project template, which might be a better starting point for me.
Regarding the issue above I didn't made any changes to the project and I only followed the steps in the readme for building and running.

I think an even better starting point might be the coffee editor example, because I also need a tree editor and dsl editor: https://github.com/eclipse-emfcloud/coffee-editor

**Comment by ndoschek** [comment]
> But the example you linked doesn't include an ecore editor right?

Yes that is correct, it works with a simple custom EMF model.

Regarding the ecore editor, please note that the `@eclipse-emfcloud/ecore-glsp` repository contains a demonstrator for showing an editor for Ecore models. Thus, we only focus on what’s relevant for the demonstration under a controlled environment. If you are interested in transforming this demonstrator into an adoptable state, e.g. by funding the development work or working on it yourself, please let us know!


> Regarding the issue above I didn't made any changes to the project and I only followed the steps in the readme for building and running.

About your issue, I noticed in your attached log that the `*.enotation` resources are not correctly loaded (which then explains the error message, as changes cannot be executed on the notation resources).
See for example the following log line: `DEBUG DefaultModelResourceManager  - Could not load resource with URI: /.../*.enotation`.
This could be caused for example by the Model Server not being able to load the notation model package configuration. You could investigate this further by debugging the [`EcoreModelResourceManager#loadSourceResources`](https://github.com/eclipse-emfcloud/ecore-glsp/blob/3f0d45204371d4aaef0f43bd8cdcf2c6b2bda082/server/org.eclipse.emfcloud.ecore.modelserver/src/main/java/org/eclipse/emfcloud/ecore/modelserver/EcoreModelResourceManager.java#L61) and check why the notation resources cannot be loaded.

**Comment by ndoschek** [comment]
This issue seems to have staled, if you are still encountering issues, please feel free to re-open, thanks!
