### ISSUE TITLE
[Model Server] ModelServer connection time out

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-emfcloud/ecore-glsp#70]
The Jetty server quickly times out; so the GLSP/ModelServer quickly becomes unusable:

```
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It seems that sometimes, the connection can be recovered, and sometimes it can't. We should clarify if this timeout is intentional; or if we should keep the GLSP-to-ModelServer connection alive (As we do for the Client-to-GLSP Connection). If transient state is maintained by the ModelServer, and is lost when the connection times out, then we should definitely keep the connection alive.

**Comment by CamilleLetavernier** [comment]
Also, I've seen this quick timeout of 30 seconds, but also a longer timeout of 300 seconds (5 minutes). Maybe we can recover from the short one; but not from the long one? To be investigated/clarified

**Comment by CamilleLetavernier** [comment]
The Timeouts have been fixed on the Modelserver branch
